insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Alajuela',21,211);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San José',21,212);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Carrizal',21,213);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Antonio',21,214);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Guácima',21,215);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Isidro',21,216);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Sabanilla',21,217);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Rafael',21,218);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Río Segundo',21,219);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Desamparados',21,2110);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Turrúcares',21,21111);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Tambor',21,21121);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Garita',21,21131);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Sarapiquí',21,21141);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Atenas',25,251);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Jesús',25,252);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Mercedes',25,253);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Isidro',25,254);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Concepción',25,255);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San José',25,256);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Santa Eulalia',25,257);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Escobal',25,258);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Grecia',23,231);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Isidro',23,232);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San José',23,233);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Roque',23,234);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Tacares',23,235);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Puente de Piedra',23,237);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Bolívar',23,238);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Rafael',215,2151);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Buenavista',215,2152);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Cote',215,2153);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Katira',215,2154);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Los Chiles',214,2141);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Caño Negro',214,2142);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('El Amparo',214,2143);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Jorge',214,2144);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Naranjo',26,261);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Miguel',26,262);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San José',26,263);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Cirrí Sur',26,264);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Jerónimo',26,265);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Juan',26,266);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('El Rosario',26,267);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Palmitos',26,268);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Orotina',29,291);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('El Mastate',29,292);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Hacienda Vieja',29,293);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Coyolar',29,294);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('La Ceiba',29,295);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Palmares',27,271);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Zaragoza',27,272);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Buenos Aires',27,273);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Santiago',27,274);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Candelaria',27,275);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Esquipulas',27,276);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('La Granja',27,277);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Pedro',28,281);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Juan',28,282);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Rafael',28,283);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Carrillos',28,284);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Sabana Redonda',28,285);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Río Cuarto',216,2161);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Santa Rita',216,2162);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Santa Isabel',216,2163);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Quesada',210,2101);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Florencia',210,2102);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Buenavista',210,2103);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Aguas Zarcas',210,2104);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Venecia',210,2105);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Pital',210,2106);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('La Fortuna',210,2107);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('La Tigra',210,2108);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('La Palmera',210,2109);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Venado',210,21010);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Cutris',210,21011);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Monterrey',210,21012);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Pocosol',210,21013);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Mateo',24,241);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Desmonte',24,242);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Jesús María',24,243);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Labrador',24,244);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Ramón',22,221);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Santiago',22,222);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Juan',22,223);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Piedades Norte',22,224);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Piedades Sur',22,225);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Rafael',22,226);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Isidro',22,227);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Los Ángeles',22,228);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Alfaro',22,229);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Volio',22,2210);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Concepción',22,2211);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Zapotal',22,2212);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Peñas Blancas',22,2213);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Lorenzo',22,2214);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Sarchí Norte',212,2121);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Sarchí Sur',212,2122);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Toro Amarillo',212,2123);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Pedro',212,2124);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Rodríguez',212,2125);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Upala',213,2131);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Aguas Claras',213,2132);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San José o Pizote',213,2133);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Bijagua',213,2134);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Delicias',213,2135);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Dos Ríos',213,2136);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Yolillal',213,2137);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Canalete',213,2138);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Zarcero',211,2111);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Laguna',211,2112);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Tapezco',211,2113);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Guadalupe',211,2114);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Palmira',211,2115);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Zapote',211,2116);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Brisas',211,2117);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Pacayas',36,361);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Cervantes',36,362);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Capellades',36,363);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Oriental',31,311);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Occidental',31,312);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Carmen',31,313);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Nicolás',31,314);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Aguacaliente o San Francisco',31,315);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Guadalupe o Arenilla',31,316);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Corralillo',31,317);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Tierra Blanca',31,318);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Dulce Nombre',31,319);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Llano Grande',31,3110);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Quebradilla',31,3111);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Tejar',38,381);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Isidro',38,382);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Tobosi',38,383);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Patio de Agua',38,384);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Juan Viñas',34,341);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Tucurrique',34,342);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Pejibaye',34,343);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Tres Ríos',33,331);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Diego',33,332);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Juan',33,333);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Rafael',33,334);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Concepción',33,335);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Dulce Nombre',33,336);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Ramón',33,337);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Río Azul',33,338);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Rafael',37,371);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Cot',37,372);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Potrero Cerrado',37,373);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Cipreses',37,374);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Santa Rosa',37,375);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Paraíso',32,321);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Santiago',32,322);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Orosi',32,323);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Cachí',32,324);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Llanos de Santa Lucía',32,325);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Turrialba',35,351);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('La Suiza',35,352);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Peralta',35,353);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Santa Cruz',35,354);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Santa Teresita',35,355);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Pavones',35,356);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Tuis',35,357);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Tayutic',35,358);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Santa Rosa',35,359);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Tres Equis',35,3510);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('La Isabel',35,3511);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Chirripó',35,3512);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Las Juntas',57,571);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Sierra',57,572);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Juan',57,573);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Colorado',57,574);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Bagaces',54,541);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Fortuna',54,542);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Mogote',54,543);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Río Naranjo',54,544);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Cañas',56,561);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Palmira',56,562);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Miguel',56,563);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Bebedero',56,564);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Porozal',56,565);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Filadelfia',55,551);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Palmira',55,552);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Sardinal',55,553);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Belén',55,554);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Hojancha',511,5111);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Monte Romo',511,5112);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Puerto Carrillo',511,5113);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Huacas',511,5114);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Matambú',511,5115);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('La Cruz',510,5101);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Santa Cecilia',510,5102);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Garita',510,5103);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Santa Elena',510,5104);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Liberia',51,511);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Cañas Dulces',51,512);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Mayorga',51,513);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Nacascolo',51,514);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Curubandé',51,515);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Carmona',59,591);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Santa Rita',59,592);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Zapotal',59,593);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Pablo',59,594);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Porvenir',59,595);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Bejuco',59,596);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Nicoya',52,521);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Mansion',52,522);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Antonio',52,523);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Quebrada Honda',52,524);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Samara',52,525);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Nosara',52,526);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Belén de Nosarita',52,527);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Santa Cruz',53,531);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Bolsón',53,532);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Veintisiete de Abril',53,533);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Tempate',53,534);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Cartagena',53,535);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Cuajiniquil',53,536);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Diria',53,537);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Cabo Velas',53,538);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Tamarindo',53,539);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Tilarán',58,581);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Quebrada Grande',58,582);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Tronadora',58,583);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Santa Rosa',58,584);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Líbano',58,585);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Tierras Morenas',58,586);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Arenal',58,587);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Barva',42,421);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Pedro',42,422);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Pablo',42,423);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Roque',42,424);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Santa Lucía',42,425);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San José de la Montaña',42,426);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Antonio',47,471);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Rivera',47,472);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('La Asunción',47,473);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Joaquín',48,481);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Barrantes',48,482);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Llorente',48,483);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Heredia',41,411);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Mercedes',41,412);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Francisco',41,413);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Ulloa',41,414);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Varablanca',41,415);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Isidro',46,461);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San José',46,462);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Concepción',46,463);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Francisco',46,464);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Pablo',49,491);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Rincón de Sabanilla',49,492);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Rafael',45,451);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Josecito',45,452);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Santiago',45,453);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Angeles',45,454);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Concepción',45,455);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Santa Bárbara',44,441);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Pedro',44,442);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Juan',44,443);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Jesús',44,444);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Santo Domingo',44,445);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Purabá',44,446);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Santo Domingo',43,431);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Vicente',43,432);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Miguel',43,433);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Paracito',43,434);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Santo Tomás',43,435);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Santa Rosa',43,436);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Tures',43,437);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Pará',43,438);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Puerto Viejo',410,4101);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('La Virgen',410,4102);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Horquetas',410,4103);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Llanuras del Gaspar',410,4104);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Cureña',410,4105);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Guácimo',76,761);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Mercedes',76,762);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Pocora',76,763);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Río Jiménez',76,764);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Duacarí',76,765);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Limón',71,711);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Valle La Estrella',71,712);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Río Blanco',71,713);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Matama',71,714);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Matina',75,751);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Batán',75,752);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Carrandi',75,753);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Guápiles',72,721);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Jiménez',72,722);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('La Rita',72,723);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Roxana',72,724);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Cariari',72,725);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Colorado',72,726);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('La Colonia',72,727);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Siquirres',73,731);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Pacuarito',73,732);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Florida',73,733);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Germania',73,734);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Cairo',73,735);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Alegría',73,736);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Bratsi',74,741);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Sixaola',74,742);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Cahuita',74,743);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Telire',74,744);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Buenos Aires',63,631);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Volcan',63,632);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Potrero Grande',63,633);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Boruca',63,634);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Pilas',63,635);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Colinas',63,636);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Changena',63,637);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Briolley',63,638);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Brunka',63,639);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Corredor',610,6101);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('La Cuesta',610,6102);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Canoas',610,6103);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Laurel',610,6104);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Vito',68,681);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Sabalito',68,682);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Aguabuena',68,683);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Limóncito',68,684);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Pittier',68,685);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Gutiérrez Braun',68,686);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Espíritu Santo',62,621);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Juan Grande',62,622);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Macacona',62,623);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Rafael',62,624);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Jerónimo',62,625);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Caldera',62,626);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Jacó',611,61111);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Tarcoles',611,61121);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Golfito',67,671);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Puerto Jiménez',67,672);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Guaycará',67,673);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Pavón',67,674);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Miramar',64,641);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('La Unión',64,642);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Isidro',64,643);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Puerto Cortés',65,651);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Palmar',65,652);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Sierpe',65,653);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Bahia Ballena',65,654);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Piedras Blancas',65,655);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Bahía Drake',65,656);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Parrita',69,691);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Puntarenas',61,611);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Pitahaya',61,612);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Chomes',61,613);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Lepanto',61,614);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Paquera',61,615);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Manzanillo',61,616);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Guacimal',61,617);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Barranca',61,618);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Monte Verde',61,619);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Isla del Coco',61,6110);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Cobano',61,6111);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Chacarita',61,6112);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Chira',61,6113);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Acapulco',61,6114);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('El Roble',61,6115);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Arancibia',61,6116);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Quepos',66,661);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Savegre',66,662);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Naranjito',66,663);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Ignacio',112,1121);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Guaitil',112,1122);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Palmichal',112,1123);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Cangrejal',112,1124);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Sabanillas',112,1125);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Alajuelita',110,1101);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Josecito',110,1102);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Antonio',110,1103);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Concepción',110,1104);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Felipe',110,1105);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Aserrí',16,161);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Tarbaca',16,162);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Vuelta de Jorco',16,163);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Gabriel',16,164);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Legua',16,165);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Monterrey',16,166);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Salitrillos',16,167);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Curridabat',118,1181);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Granadilla',118,1182);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Sánchez',118,1183);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Tirrases',118,1184);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Desamparados',13,131);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Miguel',13,132);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Juan de Dios',13,133);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Rafael Arriba',13,134);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Antonio',13,135);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Frailes',13,136);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Patarrá',13,137);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Cristóbal',13,138);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Rosario',13,139);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Damas',13,1310);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Rafael Abajo',13,1311);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Gravilias',13,1312);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Los Guido',13,1313);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Santa María',117,1171);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Jardín',117,1172);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Copey',117,1173);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Escazú',12,121);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Antonio',12,122);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Rafael',12,123);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Guadalupe',18,181);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Francisco',18,182);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Calle Blancos',18,183);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Mata de Plátano',18,184);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Ipís',18,185);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Rancho Redondo',18,186);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Purral',18,187);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Pablo',120,1201);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Andrés',120,1202);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Llano Bonito',120,1203);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Isidro',120,1204);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Santa Cruz',120,1205);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Antonio',120,1206);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Pedro',115,1151);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Sabanilla',115,1152);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Mercedes',115,1153);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Rafael',115,1154);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Colón',17,171);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Guayabo',17,172);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Tabarcia',17,173);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Piedras Negras',17,174);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Picagres',17,175);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Jaris',17,176);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Quitirrisí',17,177);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Vicente',114,1141);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Jerónimo',114,1142);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('La Trinidad',114,1143);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Isidro de El General',119,1191);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('El General',119,1192);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Daniel Flores',119,1193);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Rivas',119,1194);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Pedro',119,1195);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Platanares',119,1196);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Pejibaye',119,1197);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Cajón',119,1198);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Barú',119,1199);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Río Nuevo',119,11910);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Páramo',119,11911);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('La Amistad',119,11912);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Santiago',14,141);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Mercedes Sur',14,142);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Barbacoas',14,143);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Grifo Alto',14,144);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Rafael',14,145);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Candelarita',14,146);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Desamparaditos',14,147);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Antonio',14,148);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Chires',14,149);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Carmen',11,111);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Merced',11,112);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Hospital',11,113);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Catedral',11,114);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Zapote',11,115);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Francisco de Dos Ríos',11,116);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Uruca',11,117);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Mata Redonda',11,118);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Pavas',11,119);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Hatillo',11,1110);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Sebastián',11,11112);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Santa Ana',19,191);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Salitral',19,192);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Pozos',19,193);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Uruca',19,194);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Piedades',19,195);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Brasil',19,196);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Marcos',15,151);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Lorenzo',15,152);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Carlos',15,153);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Juan',113,1131);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Cinco Esquinas',113,1132);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Anselmo Llorente',113,1133);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('León XIII',113,1134);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Colima',113,1135);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Pablo',116,1161);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Pedro',116,1162);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Juan de Mata',116,1163);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Luis',116,1164);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Carara',116,1165);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Isidro',111,1111);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('San Rafael',111,1112);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Dulce Nombre de Jesús',111,1113);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Patalillo',111,1114);
insert into correosTX.dbo.DISTRITOS(nombreDistrito, idCanton, idDistrito) values ('Cascajal',111,1115);
