INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (1, 'Corcovado', 'Avenida Central, frente al Banco Nacional', 114);
INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (2, 'Zancudo', 'Calle 5, diagonal al supermercado La Amistad', 117);
INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (3, 'Cahuita', 'Al costado oeste del parque municipal', 121);
INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (4, 'Pavones', 'Frente a la estación de servicio Delta', 119);
INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (5, 'Volcán Poás', 'Cerca de la Plaza de la Cultura', 115);
INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (6, 'Negra', 'Al lado de la tienda de artesanías El Mercadito', 112);
INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (7, 'Uvita', 'Avenida 3, contiguo al teatro municipal', 111);
INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (8, 'Juan Castro Blanco', '200 metros norte del hospital regional', 116);
INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (9, 'Chirripó', 'Calle 8, detrás del mercado central', 113);
INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (10, 'Braulio Carrillo', '100 metros oeste de la estación de buses', 118);
INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (11, 'La Amistad', 'Frente a la terminal de trenes', 414);
INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (12, 'Carrillo', 'Diagonal al colegio técnico', 425);
INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (13, 'Hermosa', 'Boulevard principal, cerca de la iglesia', 413);
INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (14, 'Tapantí', 'Sobre la carretera principal, sector este', 411);
INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (15, 'Matapalo', 'Esquina noreste del parque central', 412);
INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (16, 'Diría', 'Contiguo al museo histórico', 422);
INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (17, 'Palo Verde', 'Frente al estadio municipal', 421);
INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (18, 'San Juanillo', 'Calle 12, costado sur del mercado', 321);
INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (19, 'Gandoca-Manzanillo', 'Edificio Esmeralda, segundo piso', 313);
INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (20, 'Avellanas', 'Sobre la avenida 7, frente al banco estatal', 311);
INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (21, 'Monteverde', 'Barrio Las Flores, detrás de la farmacia', 312);
INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (22, 'Flamingo', 'Al costado oeste del estadio municipal', 314);
INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (23, 'Los Quetzales', 'Avenida Norte, cerca del centro comercial', 315);
INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (24, 'Junquillal', 'Esquina con la avenida principal, tercer piso', 316);
INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (25, 'Isla del Coco', 'Junto a la estación de policía central', 317);
INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (26 , 'Bejuco', 'Sobre la calle 10, cerca del mercado de abastos', 219);
INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (27 , 'Malpaís', 'Avenida de los árboles, junto a la biblioteca', 215);
INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (28 , 'Carara', 'En el boulevard sur, local 3', 216);
INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (29 , 'Coyote', 'Edificio Plaza Centro, oficina 201', 217);
INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (30 , 'Ostional', 'Avenida Los Pinos, al lado del cine', 213);
INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (31 , 'Bonita', 'Sector comercial, al costado del mall', 218);
INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (32 , 'Ventanas', 'Junto al parque ecológico', 222);
INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (33 , 'Rajada', 'Edificio Vista Mar, segundo nivel', 224);
INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (34 , 'Montezuma', 'Avenida Central, al lado de la universidad', 225);
INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (35 , 'Santa Teresa', 'En la rotonda principal, edificio moderno', 611);
INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (36 , 'Conchal', 'Calle comercial, local 18', 612);
INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (37 , 'Tortuguero', 'Sobre la avenida 5, en la esquina del parque', 613);
INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (38 , 'Manuel Antonio', 'Calle costera, local frente al mar', 614);
INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (39, 'Lajas', 'Frente a Atlantis Plaza', 122);
INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (40, 'Rincón de la Vieja', 'Avenida de los museos, junto a la biblioteca central', 524);
INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (41, 'Barra Honda', 'Calle las Palmas, frente al centro cultural', 531);
INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (42, 'Tenorio', 'Esquina sur del parque ecológico', 543);
INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (43, 'Guayabo', 'Avenida del comercio, al lado de la feria artesanal', 621);
INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (44, 'Cocos Island', 'Bulevar del puerto, oficina 301', 634);
INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (45, 'La Selva', 'Plaza central, en el edificio rojo', 711);
INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (46, 'Braulio Carrillo', 'Zona industrial, contiguo a la fábrica de textiles', 723);
INSERT INTO correosTX.dbo.OFICINA (idOficina, nombre, direccionExacta, idDistrito) VALUES (47, 'Cahuita Norte', 'Frente a la estación de trenes antiguas', 735);
